source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '8.0'

link_with 'zDribbble', 'zDribbbleTests'

pod 'Mantle'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'JTAlertView'